/**
 * action types
 */
export const SET_IS_SHOW_MENU = 'menu/SET_IS_SHOW_MENU'

export const SET_OPERATEJSON = 'menu/SET_OPERATEJSON'

export const UPDATE_OVERWRITE_STATUS = 'menu/UPDATE_OVERWRITE_STATUS'

export const UPDATE_CREATE_FILE_STATUS = 'menu/UPDATE_CREATE_FILE_STATUS'

export const UPDATE_OPEN_FILE_STATUS = 'menu/UPDATE_OPEN_FILE_STATUS'