export const LOAD_FILE = 'main/LOAD_FILE'

export const SET_CUR_COMPONENT = 'main/SET_CUR_COMPONENT'

export const UPDATE_NOTE = 'main/UPDATE_NOTE'

export const UPDATE_PRINT = 'main/UPDATE_PRINT'

export const UPDATE_FILE_TITLE = 'main/UPDATE_FILE_TITLE'

export const UPDATE_NAME = 'main/UPDATE_NAME'

export const UPDATE_SETTING = 'main/UPDATE_SETTING'

export const INIT_NOTE = 'main/INIT_NOTE'

export const UPDATE_WIDTH = 'main/UPDATE_WIDTH'

export const UPDATE_IS_BOLD = 'main/UPDATE_IS_BOLD'

export const UPDATE_IS_ITALIC = 'main/UPDATE_IS_ITALIC'

export const UPDATE_IS_UNDERLINE = 'main/UPDATE_IS_UNDERLINE'

export const UPDATE_CUR_COLOR = 'main/UPDATE_CUR_COLOR'

export const OFF_FORCECHANGE = 'main/OFF_FORCECHANGE'

export const ON_FORCECHANGE = 'main/ON_FORCECHANGE'

export const SHOW_TITLE_ALERT_DIALOG = 'main/SHOW_TITLE_ALERT_DIALOG'

export const SHOW_SAVED_ALERT_DIALOG = 'main/SHOW_SAVED_ALERT_DIALOG'

export const SHOW_OVERWRITE_CONFIRM_DIALOG = 'main/SHOW_OVERWRITE_CONFIRM_DIALOG'

export const SHOW_CREATE_FILE_CONFIRM_DIALOG = 'main/SHOW_CREATE_FILE_CONFIRM_DIALOG'

export const UPDATE_IS_OPEN_FILE = 'main/UPDATE_IS_OPEN_FILE'

export const UPDATE_IS_NEW_FILE  = 'main/UPDATE_IS_NEW_FILE'

export const SHOW_ONLY_ENGLISH_ALERT_DIALOG = 'main/SHOW_ONLY_ENGLISH_ALERT_DIALOG'

export const SHOW_ADD_SEGMENT_ALERT_DIALOG = 'main/SHOW_ADD_SEGMENT_ALERT_DIALOG'

export const UPDATE_OVER_ONE_PAGE = 'main/UPDATE_OVER_ONE_PAGE'

export const SET_OVER_PAGE_ID = 'main/SET_OVER_PAGE_ID'

export const UPDATE_IS_CHANGE_FORMAT = 'main/UPDATE_IS_CHANGE_FORMAT'

export const SET_OLD_SETTING = 'main/SET_OLD_SETTING'

export const SHOW_CANNOT_CHANGE_SETTING_ALERT_DIALOG = 'main/SHOW_CANNOT_CHANGE_SETTING_ALERT_DIALOG'

export const SET_ALERT_MESSAGE = 'main/SET_ALERT_MESSAGE'

export const UPDATE_JA_INPUTING = 'main/UPDATE_JA_INPUTING'

export const UPDATE_IS_CHANGE_TYPE = 'main/UPDATE_IS_CHANGE_TYPE'

export const SET_OLD_TYPE = 'main/SET_OLD_TYPE'

export const FINISH_PRINT = 'main/FINISH_PRINT'

export const SET_FOCUS_SEGMENT = 'main/SET_FOCUS_SEGMENT'