export const LOAD_FILE = 'main/LOAD_FILE'

export const SET_CUR_SEGMENT_NO = 'main/SET_CUR_SEGMENT_NO'

export const SET_CUR_COMPONENT = 'main/SET_CUR_COMPONENT'

export const UPDATE_NOTE = 'main/UPDATE_NOTE'

export const UPDATE_PRINT = 'main/UPDATE_PRINT'

export const UPDATE_FILE_TITLE = 'main/UPDATE_FILE_TITLE'

export const UPDATE_NAME = 'main/UPDATE_NAME'

export const UPDATE_SETTING = 'main/UPDATE_SETTING'

export const INIT_NOTE = 'main/INIT_NOTE'

export const UPDATE_WIDTH = 'main/UPDATE_WIDTH'

export const UPDATE_IS_BOLD = 'main/UPDATE_IS_BOLD'

export const UPDATE_IS_ITALIC = 'main/UPDATE_IS_ITALIC'

export const UPDATE_IS_UNDERLINE = 'main/UPDATE_IS_UNDERLINE'

export const UPDATE_CUR_COLOR = 'main/UPDATE_CUR_COLOR'

export const SHOW_TITLE_ALERT_DIALOG = 'main/SHOW_TITLE_ALERT_DIALOG'

export const SHOW_SAVED_ALERT_DIALOG = 'main/SHOW_SAVED_ALERT_DIALOG'

export const SHOW_OVERWRITE_CONFIRM_DIALOG = 'main/SHOW_OVERWRITE_CONFIRM_DIALOG'

export const SHOW_CREATE_FILE_CONFIRM_DIALOG = 'main/SHOW_CREATE_FILE_CONFIRM_DIALOG'

export const UPDATE_IS_OPEN_FILE = 'main/UPDATE_IS_OPEN_FILE'

export const UPDATE_IS_NEW_FILE  = 'main/UPDATE_IS_NEW_FILE'

export const SHOW_PRINT_ERROR_DIALOG = 'main/SHOW_PRINT_ERROR_DIALOG'

export const UPDATE_JA_INPUTING = 'main/UPDATE_JA_INPUTING'

export const FINISH_PRINT = 'main/FINISH_PRINT'
